#!/usr/bin/env bash
# Display listening ports
PORT=8080
a=$(netstat -plnt | grep $PORT | awk '{print $6}')
#echo $a;exit
while [ "$a" != "LISTEN" ]
do
 (( PORT=PORT+1 ))
 printf "Port number is $PORT\n"
done
#run command

